name: api

on:
  pull_request:
  push:

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: test
