name: git

on:
  pull_request:

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      -
        name: Set up Go workspace
        run: |
          go work init
          go work use . api git
      -
        name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          workdir: git
          args: -v build test
